### PR TITLE
FAB component

### PR DESCRIPTION
**Pull request by Tharon-C**
Depends on Tooltip PR #65 
Adds the FAB (Floating Action Button) to lib and adds an example to the guide.

### CODE REVIEW

**Comment by lenards** [comment]
[When We Was](https://en.wikipedia.org/wiki/When_We_Was_Fab) [FAB](https://www.youtube.com/watch?v=dsyfvYyxjp8)

**Comment by lenards** [comment]
@Tharon-C - can we consider rebasing this onto master now to conflicts?

**Comment by Tharon-C** [comment]
~Hold on accepting this, I have to fix a bad merge~

All good :+1:

**Comment by lenards** [comment]
I'm curious why the Floating Action Button is implemented as an ES6 Class instead of using `react-create-class`?

**Comment by Tharon-C** [comment]
I actually did that before you and I talked about using the `react-create-class` module. I don't have a great reason  for it other than "everyone else is doing it" so I (begrudgingly) fell in line with the herd. 

I can switch it to use the createClass module though.

**Review by lenards — COMMENTED** [review]
In this situation, if the cyverse-ui `<FAB />` "isA" FloatingActionButton, meaning it extends the one available in material-ui, I could understand why ES6 classes are used (so that it can "extend" it). 

But in the implementation provided by the "hasA" relationship because it is "using" (e.g. delegating to) the material-ui component. You could also consider it "wrapping" the third-party component (and encapsulating it, nicely, those protecting those using cyverse-ui from changes in the interface of the that component). 

I think the pull request is fine to merge. But it would be good to know there is a deviation from the existing components.

**Comment by lenards** [comment]
_"To match the community norms"_ is a fair answer.

**Comment by lenards** [comment]
Right now, I would keep it inline with the component library's other components. 

We can always consider a codemod in the future to make the components more consistent with the React community patterns.

**Comment by lenards** [comment]
I'm fine with merging as is - it's up to you. 

Merge when you are ready. :shipit:

**Comment by Tharon-C** [comment]
Thank you! I'll change to createClass and merge. Refactoring all at once to es6 class in a separate PR is better than introducing inconsistency in this one.

**Comment by lenards** [comment]
I trust your call on this. Thanks for adding me for review. Glad to see all the progress.

**Pull request merged**
