### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by Tharon-C**
I'm breaking up a bunch of work on the @next branch into more manageable PRs.

This is a general catch all of a few small changes:
* Include Ramda in package.json
  * Not sure why we are even building in travis because we import it [on this line](https://github.com/cyverse/cyverse-ui/blob/master/guide/src/examples/ThemeColorsEx.js#L2)
* Use shorthand object syntax to get named functions
  *  Not sure if this is the same as the es2015 feature or if this is babel / jsx behaviour because in this case we don't have to declare a variable first. This looks better IMO and we get named functions in stacktraces for free. ie: `{ name() }` equates to `{ name: function name()}`
* Fix build script to use correct theme path
  * The makeTheme.js script was moved without updating the build script. Because we published a build that had the theme already built we didn't hit this but changes to the theme exposed the issue.
* Move HOC import above components.
  * I like import order to be libs / utility functions, HOC, components from libs, components. There are probably different views on this.

### CODE REVIEW

**Comment by lenards** [comment]
Okay - so this is interesting; it is misleading (and, **totally** my fault). 

So we are not building the `cyverse-ui` library on Travis, we are building the Style Guide, you can see the Style Guide is using [`cyverse-ui` is using `0.0.1`](https://github.com/cyverse/cyverse-ui/blob/master/guide/package.json#L20). I think we want to shift the [Style Guide to using a `0.*.*`](https://github.com/cyverse/troposphere/blob/zesty-zapdos/package.json#L38) (which would keep it up to the latest _available_ module release within `npm`. 

🔑 key point here is that the Style Guide is using the published version within npm, not the latest code within the repository (**very** misleading).

**Comment by lenards** [comment]
We _could_ define the Travis build such that it did an `npm link`, and mimicked more closely the [installation suggested in the Style Guide README](https://github.com/cyverse/cyverse-ui/tree/master/guide#installation). I opted for a more stable definition of the Style Guide approach; though, I made that decision without a huge amount of contemplation.

**Comment by lenards** [comment]
📝 one note, we don't have `eslint` configured yet on either the library nor the Style Guide - so that's something to consider as well. There is a _very_ simple [`.eslintrc`](https://github.com/cyverse/cyverse-ui/blob/master/.eslintrc), but it is not going to be run when doing a Travis auto-deploy.

If it is acceptable for lint violation in the current master branch, that can be added quite easily.

**Comment by Tharon-C** [comment]
Good catch re: CY_UI version. We should talk more in a different thread. There are a number of things to consider. Jason has some insight to offer as well. 

As for the linting, yes! Should have been the first thing I did.

**Comment by lenards** [comment]
@Tharon-C / @jchansen  - I'd encourage use to use [the C4 notion](https://rfc.zeromq.org/spec:42/C4/) "code as conversation" (paraphrasing a bit) to offer up approaches as pull requests (a la "demonstration defeats discussion").

**Pull request merged**
