### PR TITLE
Include only built files

### PR DESCRIPTION
**Pull request by cdosborn**
This removes the .babelrc and others (unanticipated in the future :D)

### CODE REVIEW

**Comment by Tharon-C** [comment]
Sorry I didn't see this. Is this still relevant? 
I believe would need to include `!icons/*js` ,`!utils/*.js` and `!styles/*.js`  as the `!` at least in `.gitignore` doesn't override more than one level deep. Assume you know this though because you didn't exclude `src/` or `guide/`.

**Comment by lenards** [comment]
It appears this is still relevant since an `npm run build` will create `*.js` files within the root of the repository. I think we can address the other cases in a follow-up pull request.

**Comment by lenards** [comment]
`.npmignore` has the same rules as `.gitignore` \[[src](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)\]
To-do:
- [x] !icons/*js
- [x] !utils/*.js
- [x] !styles/*.js

**Comment by lenards** [comment]
#35 address concerns about the other sub-directories.

**Comment by cdosborn** [comment]
Thanks

**Pull request merged**
